require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs = ['lib', 'test']
  t.name = 'test:unit:all'
  t.warning = true
  t.test_files = FileList['test/unit_*.rb']
end

FileList['test/unit_*.rb'].each do |p|
  name = p.split('_').last.split('.').first
  Rake::TestTask.new do |t|
    t.libs = ['lib', 'test']
    t.name = "test:unit:#{name}"
    t.warning = true
    t.test_files = [p]
  end
end
